[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["David \"Ziggiyzoo\" <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.10"
numpy = "^1.22.2"
replit = "^3.2.4"
discord = "^1.7.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
